---
name: Mineflow
main: aieuo\mineflow\Main
version: 0.0.1
api: 3.0.0
load: POSTWORLD
author: aieuo
permissions:
  mineflow.command.mineflow:
    default: op
    description: "mineflow.command.mineflow"
...